### ISSUE TITLE
Convertor of cli_tool not working

### ISSUE THREAD

**Issue by RishabhBhatnagar** [spdx/tools-python#152]
This is a follow-up of https://github.com/spdx/tools-python/pull/148#discussion_r509255423 .

> I've tried running the convertor. But couldn't run it successfully for any of the ways defined in the README.md file.
>
> The following are the ways I tried and the errors they've raised.
>
>     convertor --infile file.rdf --outfile output.json raised following error:
>     Error: Invalid value for '--to' / '-t': invalid choice: undefined. (choose from json, rdf, yaml, xml, tag)
>     convertor --from rdf file.rdf --to json output.json raised following error:
>     spdx.parsers.builderexceptions.FileTypeError: INPUT FILETYPE NOT SUPPORTED. (only RDF and TAG format supported)
>     convertor -f rdf file.rdf -o output.json raised following error:
>     Error: Invalid value for '--to' / '-t': invalid choice: undefined. (choose from json, rdf, yaml, xml, tag)
>
> If you think I might've made some mistake while running the tool, you can check how I ran it in this [google colab file](https://colab.research.google.com/drive/1UUx2grrfII71fwCevYgbtCOted5qkS4t?usp=sharing)

**Comment by TraceyOnim** [comment]
Is there any follow-up on the issue? I'm also facing the same error .

**Comment by pombredanne** [comment]
@TraceyOnim not yet... help would be mucho welcomed!

**Comment by nicoweidner** [comment]
It looks like the issues reported here were actually fixed in https://github.com/spdx/tools-python/pull/174; the errors are gone. However, the same PR caused an issue with the first example where both `infile` and `outfile` is used. That is caught by [this block](https://github.com/spdx/tools-python/blob/3efab86fd735cb527032c959417668bc9a2d3de1/spdx/cli_tools/convertor.py#L79-L81) and just prints the help message.

**Comment by meretp** [comment]
I'll have a look.

**Comment by nicoweidner** [comment]
Fixed via https://github.com/spdx/tools-python/pull/235
