### ISSUE TITLE
Remove leftover tv_to_rdf.py

### ISSUE THREAD

**Issue by nicoweidner** [spdx/tools-python#229]
It seems to be that the file [tv_to_rdf.py](https://github.com/spdx/tools-python/blob/0844b34b415e1780cb2a3a51f28231b1b5502bd6/spdx/tv_to_rdf.py) just contains a special case of the conversion logic, namely converting a tag/value file to rdf - which is covered by [convertor.py](https://github.com/spdx/tools-python/blob/3efab86fd735cb527032c959417668bc9a2d3de1/spdx/cli_tools/convertor.py). `tv_to_rdf` is also not exposed as CLI tool when installing the package.

An opinion from contributors who worked on the project would be appreciated!

**Comment by meretp** [comment]
Furthermore, the file contains an error, so that the script can't be executed at present. In [line 35 ](https://github.com/spdx/tools-python/blob/c0aa92a3a4779fe189c72b5e1d85a18267f6e45a/spdx/tv_to_rdf.py#L35)it should say
`with open(outfile_name, mode="wb") as outfile` 
so that the rdf file can be written.

**Comment by meretp** [comment]
Closing this issue as the file is fixed with #316 and moved to the example folder.
