### ISSUE TITLE
Convertor warns about missing license when converting SPDXSimpleTag.tag to rdf

### ISSUE THREAD

**Issue by nicoweidner** [spdx/tools-python#233]
I am getting the following warning:
```
$ convertor -f tag data/SPDXSimpleTag.tag -o output.rdf
/home/nico/IdeaProjects/tools-python/venv/lib/python3.8/site-packages/spdx/writers/rdf.py:148: UserWarning: Missing extracted license: LicenseRef-2.0
  warnings.warn(
```
Not entirely sure what this warning is about, so I will leave it in this issue for now. It is not shown for other output formats. The created rdf file does contain a reference to the license, though without text:
```
        <ns1:licenseConcluded>
          <ns1:ConjunctiveLicenseSet rdf:nodeID="N7b9b488d98c44779a852cbe0985ac244">
            <ns1:member rdf:resource="http://spdx.org/licenses/Apache-2.0"/>
            <ns1:member>
              <ns1:ExtractedLicensingInfo rdf:nodeID="N4efe760119e54e0c9ccaa773e3d1fd07">
                <ns1:licenseId>LicenseRef-2.0</ns1:licenseId>
                <ns1:extractedText>None</ns1:extractedText>
                <ns1:licenseName>LicenseRef-2.0</ns1:licenseName>
              </ns1:ExtractedLicensingInfo>
            </ns1:member>
          </ns1:ConjunctiveLicenseSet>
        </ns1:licenseConcluded>
```

**Comment by meretp** [comment]
I had a look at this issue and this is what I have found out so far: 
- The rdf writer is the only one that creates these `ConjunctiveLicenseSet`/ `DisjunctiveLicenseSet` with these `member`-tags  for concluded and declared licenses, see [here](https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/#d46-license-expressions-in-rdf). For all other formats only the license expression is written. 
- The rdf writer checks if the concluded or declared licenses are `ExtractedLicenses`-objects, if they appear in the list of extracted licenses or if they are listed in the provided [license list ](https://github.com/spdx/tools-python/blob/main/spdx/licenses.json). If this is not the case the warning is thrown and within the `member`-tag an `ExtractedLicensingInfo`-node is written. 
From my understanding of the [spec](https://spdx.github.io/spdx-spec/v2.3/other-licensing-information-detected/) I think this should be written to `ExtractedLicensingInfo` as a separate node at document level. Since all other writer don't check the licenses in LicenseExpressions I think we should insert this kind of validation at document level before writing to any other format. 

Another question that came up for me:
- I guess we need to update the [license list ](https://github.com/spdx/tools-python/blob/main/spdx/licenses.json) regularly. Is there any workflow dealing with that or do we want to automate this?

**Comment by armintaenzertng** [comment]
The refactored version now found on main uses the `license-expression` library to handle licenses, so we don't have to take care of that anymore.
