### ISSUE TITLE
Discuss architecture rework to be more modular and future-proof

### ISSUE THREAD

**Issue by nicoweidner** [spdx/tools-python#277]
This is going to be a big issue; more on the level of an epic, if such a thing would exist on Github. I'd like to start a discussion about it first, and if there are no objections, we can create a new umbrella issue for all the smaller issues that will be required.

The core suggestions are:
- Enable separate logical paths for different SPDX versions (currently, there is no distinction at all) 
- Clearly separate layers: parser, data model, validation, writer
- Each layer should have a clear set of responsibilities

Some finer comments:
- v2.2 and v2.3 must both be supported. To my current knowledge, we can use the same parsing layer and data model, supporting all v2.3 properties. The differences will be in the validation layer (e.g. additional properties, additional checksum algorithms, different mandatory/optional properties)
- While differences between v2.2 and v2.3 are limited, v3 is expected to be completely separate
- A one-way conversion option from v2 to v3 should be added in the data model once v3 is available

I drew a diagram to help illustrate the suggested changes (available as .jpg and zipped .drawio, because Github doesn't like that format). Let's get this going so we are ready for v3 when it is released!

![tools-python_architecture](https://user-images.githubusercontent.com/66428403/201094708-1e9a018c-878f-4d78-bd95-7b874d690d1d.jpg)

[tools-python_architecture.zip](https://github.com/spdx/tools-python/files/9980749/tools-python_architecture.zip)

**Comment by nicoweidner** [comment]
Note that this plan most likely implies rewriting large parts of the Python tools. Apart from the scale of the changes, this is also due to the state that the tools are in, which is not great - to put it mildly. The parser/builder layer in particular is quite a mess that needs a complete rework to become maintainable. The writer layer is in a somewhat better state (and also smaller overall), but could still be improved significantly. The data model is sort of okay, apart from the fact that it would benefit massively from adding typing and (arguably) extracting validation into a separate layer.

Apart from the structural issues, a wide assortment of problems remains. Among others, there are many inconsistencies with the specification, missing validations, completely broken examples and bad test coverage.

**Comment by zvr** [comment]
I would actually propose to _not_ try and integrate v3 handling, but start from a blank sheet on this, armed with the experience of past work (and errors!) made.

As can be seen even in this diagram, v3 will have very little in common with v2 (different model, parsing, generating, validating, etc.), although it obviously deals with the same functionality. Trying to handle both versions (v2 and v3) will result in some Frankenstein-like underlying architecture, I fear.

**Comment by nicoweidner** [comment]
@zvr Are you saying you would keep v3 handling in a completely separate repo?
The idea (as shown in the diagram above) was to make sure to include a version parameter at each "entry point", so that internal handling can be completely separate. As you said, v3 is expected to be radically different, so I would expect that separate classes and probably a different internal structure for the parsing and other layers are required. The only interconnection is the possibility of converting from v2 to v3. Actual work on the implementation is not meant to start before v3 is released.

**Comment by zvr** [comment]
Yes, I would strongly suggest having a separate repo and library for spdx3. It is (will be) a completely different beast: not only different classes and architecture, but also different "entry points" as you say.

For conversion (if it even makes sense) a separate utility using both libraries would be enough (`spdx2.load(); spdx3.save()`, with a lot of internal knowledge of both models).

**Comment by zvr** [comment]
Sorry, I wasn't clear.  When I mentioned "entry points" above I was talking about _library_ interface, not the _CLI tools_ one.

Since both versions talk about the same abstract ideas, but with very different implementations, do you expect to have classes like `File_v2`, `File_v3`, and similarly for every entity? I believe there will not be a single one that could be reused.

And in the future, SPDXv2 will be abandoned at some point for the new version -- why keep having in the library code of only historical significance?

Conversely, what is the advantage of having both versions in a single repo?

**Comment by zvr** [comment]
Let me expand a little:

I don't know whether you have been following up the v3 discussions, but a reasonably current model can be seen at https://github.com/spdx/spdx-3-model/blob/main/model.png. It is immediately obvious that it will be completely different from SPDXv2.

I assume that this repo is about the library capable of dealing with SPDX -- not only about the command-line tools. As such, I expect people to be able to use it in order to create and process SPDX data, independent of SPDX Documents (which is not the main entity in SPDXv3 any more).

**Comment by nicoweidner** [comment]
To my knowledge, concerns about handling both v2 and v3 in the Python tools were discussed by @maxhbr and @zvr in a Zoom meeting, and it was agreed that the current plan is fine.

I will close this issue in a few days unless there are further concerns.

**Comment by nicoweidner** [comment]
Ok, maybe I misunderstood how the discussion went. Anyway, I will call this good enough to proceed for now...

**Comment by nicoweidner** [comment]
Closing this as no further discussions came up
