### ISSUE TITLE
rdf-parser fails on SPDXRdfExample-v2.2

### ISSUE THREAD

**Issue by meretp** [spdx/tools-python#323]
The rdf parser throws an IndexError (`IndexError: list index out of range`), when trying to parse the RdfExample file for spec version 2.2  from the spdx-spec repo ([here](https://github.com/spdx/spdx-spec/blob/development/v2.2.2/examples/SPDXRdfExample-v2.2.spdx.rdf.xml)).

**Comment by abhi-kr-2100** [comment]
I've successfully reproduced this error, and currently working to diagnose and fix it.

**Comment by abhi-kr-2100** [comment]
After some analysis, I've found that the body of the for loop at https://github.com/spdx/tools-python/blob/main/spdx/parsers/rdf.py#L1450 doesn't execute. As a result, `set_ext_doc_id` — the function that populates `doc.ext_document_references` — is not run.

The for loop at https://github.com/spdx/tools-python/blob/main/spdx/parsers/rdf.py#L1459 does run, but since `doc.ext_document_references` is empty, it causes an `IndexError`.

I've fixed this particular problem but the sample file still causes exceptions due to other bugs. I'm making a pull request to get feedback on whether my way of solving these problems is correct since I'm new to SPDX.

**Comment by armintaenzertng** [comment]
The example document `SPDXRdfExample-v2.2.spdx.rdf.xml` can be successfully parsed using the refactored version now found on main.
