### ISSUE TITLE
Document Compare functionality

### ISSUE THREAD

**Issue by avirlrma** [spdx/tools-python#34]
I would like to implement this functionality as a small project for understanding my targetted GSoC project a little better. I am planning of making comparision between two rdf format documents at first, then I will go on to expand for tv format as well.Let me know your thoughts on this @pombredanne , so that I can proceed.

**Comment by aviral1701** [comment]
@pombredanne Any word on this?

**Comment by aviral1701** [comment]
@sschuberth @rtgdk Can you guys take a quick look and give your feedback on this.

**Comment by rtgdk** [comment]
You are free to do so. Although, the compare functionality may require some time and understanding of the 2.1 specifications. That's why it can be included in the GSoC project along with other things.
You can find the idea for the compare tool here: https://github.com/spdx/tools/tree/master/src/org/spdx/compare
