### ISSUE TITLE
Finish package validation

### ISSUE THREAD

**Issue by armintaenzertng** [spdx/tools-python#386]
part of #307 

- [x] check if verification code is required when `files_analyzed = True` and make check for it
- [x] write tests for package verification code validation
- [x] write tests for "no `CONTAINS` or `CONTAINED_BY` relationships if `files_analyzed = False`"

**Comment by armintaenzertng** [comment]
After some research, I haven't found evidence that the verification code is mandatory if `files_analyzed = True`.
There's an open issue on the topic here: https://github.com/spdx/spdx-spec/issues/802

**Comment by armintaenzertng** [comment]
fixed by #461

**Comment by armintaenzertng** [comment]
fixed by #461

**Comment by Trolldemorted** [comment]
>After some research, I haven't found evidence that the verification code is mandatory if files_analyzed = True.
There's an open issue on the topic here: https://github.com/spdx/spdx-spec/issues/802

`spdx-tools==0.8.3` does not complain about `PackageVerificationCode` being not present, and the issue you linked also says it shouldn't be required because the cardinality is 0..1. Is the current behaviour intended? The java tooling appears to raise a warning in this case, should I open an issue there?
