### ISSUE TITLE
Release 0.7.0 created without a wheel

### ISSUE THREAD

**Issue by carstencodes** [spdx/tools-python#398]
The release 0.7.0 has been created three weeks ago, but on [pypi](https://pypi.org/project/spdx-tools/) the latest version available is 0.6.1 .

Could you please upload the latest wheel to pypi?

**Comment by nicoweidner** [comment]
This is the same issue as https://github.com/spdx/tools-python/issues/302, so I'll close this as a duplicate.
You can check up on the status in the linked issue.

In the meantime, if you are eager to try out 0.7.0, there is a rc on PyPI which is functionally identical, I believe: https://pypi.org/project/spdx-tools/0.7.0rc0/. Since it's not a release version, you'll have to install it explicitly.

**Comment by carstencodes** [comment]
@nicoweidner Sorry, did not find it explicitely in the issue list. Sorry for the inconvenience.

I am actually using git+https://github.com/spdx/tools-python.git@v0.7.0 , which is a proper workaround

**Comment by carstencodes** [comment]
@nicoweidner Yeah, I can go on and  handle the version for development purposes. But I would appreciate to release the [pdm-sbom](https://github.com/carstencodes/pdm-sbom) with a final wheel. Development should take about two months...

**Comment by nicoweidner** [comment]
@carstencodes Just for awareness: The release is finally out on PyPI: https://pypi.org/project/spdx-tools/#files
