### ISSUE TITLE
Failure to parse when licenseInfoFromFiles contains an item and filesAnalyzed is false 

### ISSUE THREAD

**Issue by jzebor** [spdx/tools-python#483]
When parsing a json file with command "pyspdxtools_parser --file <FILE>" I observed the following.

- Failure when licenseInfoFromFiles contains an item and filesAnalyzed is false. 
- Success when licenseInfoFromFiles contains an item and filesAnalyzed is true.

I interpret the following as tools can ignore licenseInfoFromFiles when filesAnalyzed is false. 
https://spdx.github.io/spdx-spec/v2.2.2/package-information/#714-all-licenses-information-from-files-field

Is failure expected when "licenseInfoFromFiles" contains an item and filesAnalyzed is false ?

Attached test cases
[files_analyzed_false.json.txt](https://github.com/spdx/tools-python/files/10737291/files_analyzed_false.json.txt)
[files_analyzed_true.json.txt](https://github.com/spdx/tools-python/files/10737292/files_analyzed_true.json.txt)

**Comment by jzebor** [comment]
FWIW - After this commit the behavior is still the same.
https://github.com/spdx/tools-python/commit/ccd0758e550b4b94acee50724b89d9845d125200

**Comment by meretp** [comment]
Short answer: yes, it is expected. In [SPDX 2.3](https://spdx.github.io/spdx-spec/v2.3/package-information/#714-all-licenses-information-from-files-field) the spec explicitly states 

Cardinality | 0..* (optional) if FilesAnalyzed (7.8) is true or omitted, 0..0 (must be omitted) if FilesAnalyzed is false.
-- | --

 In SPDX 2.2.2 this isn't as clear and I think one could argue that the tools should just ignore information if provided. But in my opinion this wouldn't be a good way, it could also be that the value of the filesAnalyzed field is falsy and should have been `true`. The failure causes the user to check his file again, which I would assume is the better choice. 
 What is your use case here? Would you disagree and think it is better if the tool would ignore the licensiInfoFromFiles (at least for spdx documents of version 2.2.2)?

**Comment by jzebor** [comment]
Thanks for the quick response.

I *think* a valid v2.2 case is for an spdx sbom generator to set licenseInfoFromFiles to "NOASSERTION" and filesAnalyzed false, which encounters the error reported. The cases where I'm seeing failures have either "NOASSERTION" OR "SOME_LICENSE" as a list item in licenseInfoFromFiles with filesAnalyzed set as false.

Since the spec for v2.3 is stronger, the current behavior seems acceptable but IMO when parsing a < v2.2 document the licenseInfoFromFiles should be ignored and not cause a parser failure.

**Comment by meretp** [comment]
Yes, I understand your point of view for v2.2. We probably won't fix this in the current codebase as it is not really a bug. But we are working on a refactored version of the tools where we strictly separate the parsing and validation layer. In the refactored version a v2.2 document with `filesAnalyzed` set to `false` and `licenseInfoFromFiles` filled with values should not cause a parsing error but probably still raise a ValidationMessage as this case is not really clear in the spec. AFAIK the aim of SPDX v2.3 was to be more specific than v2.2 and to clarify things like this. So, I think the intent (also in v2.2) was that `licenseInfoFromFiles` must be omitted. But as said since the spec here is rather ambiguous, we will only raise a `ValidationMessage` that could be ignored by the user and this should not lead to a parsing error.

**Comment by jzebor** [comment]
Your explanation is reasonable to me. Thanks.
